networks:
  oracle-laravel :

services:

  nginx:
    image: nginx:stable-alpine
    container_name: oracle-laravel-nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - php
    depends_on:
      - php
      - mysql
    networks:
      - oracle-laravel
  
  mysql:
    image: mysql:8.3.0
    container_name: oracle-laravel-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3563:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./config/mysql:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: laravel
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    mem_limit: 1g
    user: "1000:1000"
    networks:
      - oracle-laravel

  php:
    image: php:8.3.1RC3-fpm
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oracle-laravel-php
    volumes:
      - ./src:/var/www/html
    networks:
      - oracle-laravel
  
  # oracle:
  #   ## !! install the image first https://itnext.io/oracle-on-arm-mac-m1-m2-docker-images-99ed67ed6ba6
  #   image: oracle/database:19.3.0-ee-slim-faststart
  #   container_name: oracle-laravel-oracle
  #   environment:
  #       - ORACLE_USER=my_user
  #       - ORACLE_PASSWORD=my_password
  #   ports:
  #     - 1523:1521
  #     - 5500:5500
  #   networks:
  #     - oracle-laravel
